// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['bindings']['ConnectionService']['AddConnection'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['bindings']['ConnectionService']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['bindings']['ConnectionService']['Disconnect'](arg1);
}

export function GetConnections() {
  return window['go']['bindings']['ConnectionService']['GetConnections']();
}
