// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {drivers} from '../models';
import {connections} from '../models';

export function AddConnection(arg1:string,arg2:drivers.ConnectionConfig):Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<connections.ConnectionInfo>>;
