// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {drivers} from '../models';

export function AddConnection(arg1:drivers.ConnectionConfig):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;
