// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {frontend} from '../models';

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function PickFilePath(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveXLSX(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<void>;
