// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function OnStartup(arg1:context.Context):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveXLSX(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<void>;
