// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {drivers} from '../models';

export function Execute(arg1:string,arg2:string):Promise<drivers.QueryResult>;
