// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['bindings']['SchemaService']['GetColumns'](arg1, arg2, arg3);
}

export function GetDatabases(arg1) {
  return window['go']['bindings']['SchemaService']['GetDatabases'](arg1);
}

export function GetSchemas(arg1, arg2) {
  return window['go']['bindings']['SchemaService']['GetSchemas'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['bindings']['SchemaService']['GetTables'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['bindings']['SchemaService']['GetViews'](arg1, arg2);
}
