// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<Array<schema.Column>>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetSchemas(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<string>>;

export function GetViews(arg1:string,arg2:string):Promise<Array<string>>;
